In [2]:
import pandas as pd
import numpy as np
import pickle

# PDAC

## Checking that pools make sense

In [31]:
plate1 = np.load("pools/randomPDAC1/4x_5r_randomPDAC1.npy")

In [35]:
plate1.shape

(72, 68)

All 68 drugs occur 5 times

In [33]:
plate1.sum(0)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [36]:
plate1.sum(1)

array([5., 5., 5., 4., 4., 5., 5., 5., 5., 5., 5., 5., 5., 4., 5., 5., 4.,
       4., 5., 4., 5., 5., 5., 5., 4., 5., 5., 5., 4., 5., 5., 4., 5., 5.,
       5., 5., 5., 4., 5., 5., 4., 5., 5., 5., 4., 5., 5., 5., 4., 5., 5.,
       4., 4., 4., 5., 5., 5., 4., 5., 5., 4., 4., 5., 5., 5., 5., 5., 5.,
       4., 5., 5., 5.])

All pools have 4 or 5 drugs

In [37]:
np.mean(plate1.sum(1))

4.722222222222222

In [38]:
plate2 = np.load("pools/randomPDAC2/4x_5r_randomPDAC2.npy")

In [39]:
plate2.shape

(72, 68)

In [40]:
plate2.sum(0)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [41]:
plate2.sum(1)

array([5., 4., 5., 5., 5., 5., 5., 4., 5., 5., 5., 5., 5., 4., 4., 5., 5.,
       5., 5., 5., 5., 5., 5., 4., 4., 5., 4., 5., 4., 5., 5., 4., 5., 5.,
       4., 4., 5., 5., 4., 5., 5., 5., 5., 5., 5., 5., 5., 5., 4., 5., 5.,
       5., 5., 5., 5., 4., 5., 5., 5., 5., 5., 5., 4., 5., 4., 5., 4., 5.,
       4., 4., 5., 4.])

In [42]:
np.mean(plate2.sum(1))

4.722222222222222

In [3]:
final_name = "randomPDAC"
picklist = pd.read_csv("picklists/"+final_name+"_final.csv",index_col=0)
metadata = pd.read_csv("metadata/"+final_name+"_final.csv",index_col=0)
pool_key = pd.read_csv("pool_keys/"+final_name+"_final.csv",index_col=0)
with open("well_drug_dicts/"+final_name+'_final.pickle', 'rb') as handle:
    well_drug_dict = pickle.load(handle)

## Picklist

In [6]:
print("Checking number of uses of each ligand")
print(picklist['compound_name'].value_counts().values)
print("Should be using 2(96-12) = 168 destination wells in the picklist")
print(len(np.unique(picklist['destination_well'])))
print("68 source wells in the picklist")
print(len(np.unique(picklist['source_well'])))
print('check that everything goes to the correct plate')
print(np.unique(picklist['destination_plate']))

Checking number of uses of each ligand
[18 18 18 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
Should be using 2(96-12) = 168 destination wells in the picklist
168
68 source wells in the picklist
68
check that everything goes to the correct plate
['randomPDAC']


most things get used 10 times (two compressed of 5 reps), 3 positive controls get another 4x2=8 for 18 total

## Metadata

In [26]:
metadata.loc[metadata.Metadata_perturbation=="TNF"]

Metadata_Well Metadata_perturbation  Metadata_compression  \
80           K19                   TNF                     4   
81           M07                   TNF                     4   
82           M13                   TNF                     4   
83           A21                   TNF                     4   
80           M10                   TNF                     4   
81           G02                   TNF                     4   
82           G24                   TNF                     4   
83           M06                   TNF                     4   

    Metadata_replicates  quadrant  
80                    5         1  
81                    5         1  
82                    5         1  
83                    5         1  
80                    5         2  
81                    5         2  
82                    5         2  
83                    5         2

In [27]:
metadata.loc[metadata.Metadata_perturbation=="TGFB1"]

Metadata_Well Metadata_perturbation  Metadata_compression  \
72           M23                 TGFB1                     4   
73           A15                 TGFB1                     4   
74           O07                 TGFB1                     4   
75           I01                 TGFB1                     4   
72           K10                 TGFB1                     4   
73           A02                 TGFB1                     4   
74           G18                 TGFB1                     4   
75           K08                 TGFB1                     4   

    Metadata_replicates  quadrant  
72                    5         1  
73                    5         1  
74                    5         1  
75                    5         1  
72                    5         2  
73                    5         2  
74                    5         2  
75                    5         2

In [25]:
metadata.loc[metadata.Metadata_perturbation=="IFNG"]

Metadata_Well Metadata_perturbation  Metadata_compression  \
76           G21                  IFNG                     4   
77           C15                  IFNG                     4   
78           C19                  IFNG                     4   
79           A23                  IFNG                     4   
76           C10                  IFNG                     4   
77           K24                  IFNG                     4   
78           A12                  IFNG                     4   
79           C24                  IFNG                     4   

    Metadata_replicates  quadrant  
76                    5         1  
77                    5         1  
78                    5         1  
79                    5         1  
76                    5         2  
77                    5         2  
78                    5         2  
79                    5         2

In [13]:
metadata.loc[metadata.Metadata_perturbation=="media"]

Metadata_Well Metadata_perturbation  Metadata_compression  \
84           M19                 media                     4   
85           K13                 media                     4   
86           E23                 media                     4   
87           A07                 media                     4   
88           I17                 media                     4   
89           O05                 media                     4   
90           E15                 media                     4   
91           I15                 media                     4   
92           E17                 media                     4   
93           A11                 media                     4   
94           O11                 media                     4   
95           M11                 media                     4   
84           E12                 media                     4   
85           M20                 media                     4   
86           C12                 media                     4   
87           G14                 media                     4   
88           E20                 media                     4   
89           O24                 media                     4   
90           C02                 media                     4   
91           A20                 media                     4   
92           K22                 media                     4   
93           A04                 media                     4   
94           G04                 media                     4   
95           A08                 media                     4   

    Metadata_replicates  quadrant  
84                    5         1  
85                    5         1  
86                    5         1  
87                    5         1  
88                    5         1  
89                    5         1  
90                    5         1  
91                    5         1  
92                    5         1  
93                    5         1  
94                    5         1  
95                    5         1  
84                    5         2  
85                    5         2  
86                    5         2  
87                    5         2  
88                    5         2  
89                    5         2  
90                    5         2  
91                    5         2  
92                    5         2  
93                    5         2  
94                    5         2  
95                    5         2

In [9]:
print(metadata['Metadata_perturbation'].value_counts())

random2    72
random1    72
media      24
TGFB1       8
IFNG        8
TNF         8
Name: Metadata_perturbation, dtype: int64


## Well drug dictionary

In [23]:
q = well_drug_dict['quadrant1']
lens = []
for pool in q:
    lens.append(len(q[pool]))
lens = np.array(lens)
print(np.sort(lens))


[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [24]:
q

{'M1': ['BMP4', 'LPA', 'LGALS9', 'IL33', 'CXCL12'],
 'M21': ['IFNG', 'CD40LG', 'BDNF', 'IL1B', 'SPP1'],
 'E1': ['TSLP', 'TGFB3', 'IL33', 'IFNA2', 'CSF1'],
 'E9': ['RARRES2', 'FGF10', 'ADIPOQ', 'PF4'],
 'K7': ['beta-NGF', 'TRAIL', 'THBS1', 'IL7', 'IL33'],
 'O1': ['PDGF-AA', 'IL4', 'IL17A', 'FASLG', 'IL13'],
 'I7': ['IL33', 'IL15', 'INHBB', 'IL7'],
 'G23': ['HGF', 'CCL3', 'BDNF', 'IL1B', 'NOGGIN'],
 'O19': ['TNF', 'IL6', 'FGF1', 'EPO', 'ADIPOQ'],
 'K23': ['IFNA2', 'APP', 'APOA1', 'EPO'],
 'G17': ['THBS1', 'NAMPT', 'IL1A', 'BMP4'],
 'C5': ['APP', 'APOE', 'BDNF', 'IL15', 'TGFB1'],
 'A13': ['RSPO3', 'RARRES2', 'IL33', 'FASLG'],
 'M15': ['THBS1', 'IFNA2', 'GDF15', 'EGF', 'FN1'],
 'K3': ['RANKL', 'NRG1', 'FN1', 'CSF2', 'APOE'],
 'I21': ['INHBB', 'IL10', 'IGF1', 'C5'],
 'O3': ['IGF1', 'TGFB1', 'OSM', 'NRG1', 'IL22'],
 'C11': ['OSM', 'IL22', 'GDF15', 'FGF10', 'BMP4'],
 'M5': ['VEGFA', 'RSPO3', 'IL4', 'CD40LG'],
 'A17': ['RARRES2', 'IFNG', 'FGF13', 'BDNF', 'TNF'],
 'A5': ['HGF', 'FGF10', 'RSPO3'

In [29]:
print(sum(lens==0))
print(sum(lens==1))
print(sum(lens==4)+sum(lens==5))

12
12
72


In [20]:
q = well_drug_dict['quadrant2']
lens = []
for pool in q:
    lens.append(len(q[pool]))
lens = np.array(lens)
print(np.sort(lens))

[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [30]:
print(sum(lens==0))
print(sum(lens==1))
print(sum(lens==4)+sum(lens==5))

12
12
72
